[package]
authors = ["cairoliang <shuimuliang@gmail.com>"]
name = "tonic-reconnect-demo"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "helloworld-server"
path = "src/server.rs"

[[bin]]
name = "helloworld-client"
path = "src/client.rs"

[dependencies]
prost = "0.11.6"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.8.3"

[build-dependencies]
tonic-build = "0.8"
